# Generated by Django 4.0.3 on 2022-03-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deseos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='users_who_like',
        ),
        migrations.AddField(
            model_name='wish',
            name='users_who_granted',
            field=models.ManyToManyField(related_name='granted_wishes', to='deseos.user'),
        ),
    ]
