# Generated by Django 4.0.1 on 2022-03-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayudante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('userJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ayudante.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
