# Generated by Django 4.0.1 on 2022-03-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayudante', '0002_job_delete_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job',
            new_name='title',
        ),
    ]
