# Generated by Django 4.0.1 on 2022-03-09 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayudante', '0003_rename_job_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='userJob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ayudante.user'),
        ),
    ]
