# Generated by Django 4.0.1 on 2022-03-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodGender',
            field=models.CharField(choices=[('1', 'Niño'), ('2', 'Niña'), ('3', 'Unisex')], default='1', max_length=1),
        ),
    ]
