# Generated by Django 4.0.1 on 2022-03-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0002_alter_product_prodgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
