# Generated by Django 4.0.1 on 2022-03-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0003_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
