# Generated by Django 4.0.1 on 2022-03-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0004_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='typeUser',
            field=models.CharField(choices=[('1', 'ADMINISTRADOR'), ('2', 'USUARIO')], default='1', max_length=1),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
