# Generated by Django 4.0.1 on 2022-03-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0005_alter_user_typeuser_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='0-6 meses', max_length=50),
        ),
    ]
