# Generated by Django 4.0.1 on 2022-03-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0006_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('1', '0-3 meses'), ('2', '3-6 meses'), ('3', '6-12 meses'), ('4', '12-18 meses'), ('5', '18-24 meses'), ('6', '2 años'), ('7', '3 años')], default='0-6 meses', max_length=50),
        ),
    ]
