# Generated by Django 4.0.3 on 2022-03-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0011_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='typeUser',
            field=models.CharField(blank=True, choices=[('1', 'ADMINISTRADOR'), ('2', 'USUARIO'), ('3', 'ALMACENERO')], default='2', max_length=1),
        ),
    ]
