# Generated by Django 4.0.1 on 2022-03-20 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0012_alter_user_typeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('opGravada', models.DecimalField(decimal_places=2, max_digits=6)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productos', models.ManyToManyField(related_name='carritos', to='baby.Product')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='baby.user')),
            ],
        ),
    ]
