# Generated by Django 4.0.1 on 2022-03-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0016_remove_buycart_precioenvio_remove_buycart_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycart',
            name='precioEnvio',
            field=models.DecimalField(choices=[('1', 'Cerca S/.10'), ('2', 'Media Distancia S/.15'), ('3', 'Larga distancia S/.20')], decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='precioEnvio',
            field=models.DecimalField(choices=[('10', 'Cerca S/.10'), ('15', 'Media Distancia S/.15'), ('20', 'Larga distancia S/.20')], decimal_places=2, default=0, max_digits=6),
        ),
    ]
