# Generated by Django 4.0.1 on 2022-03-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0017_buycart_precioenvio_alter_boleta_precioenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='precioEnvio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='buycart',
            name='precioEnvio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
