# Generated by Django 4.0.1 on 2022-03-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0018_alter_boleta_precioenvio_alter_buycart_precioenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='precioEnvio',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
        migrations.AlterField(
            model_name='buycart',
            name='precioEnvio',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
    ]
