# Generated by Django 4.0.1 on 2022-03-22 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0019_alter_boleta_precioenvio_alter_buycart_precioenvio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='buycart',
            name='precioEnvio',
        ),
        migrations.AddField(
            model_name='boleta',
            name='items',
            field=models.ManyToManyField(related_name='carritos', to='baby.BuyCart'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios2', to='baby.user'),
        ),
        migrations.AddField(
            model_name='buycart',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
