# Generated by Django 4.0.1 on 2022-03-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0020_remove_boleta_carrito_remove_buycart_precioenvio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta',
            old_name='items',
            new_name='carrito',
        ),
    ]
