# Generated by Django 4.0.1 on 2022-03-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0021_rename_items_boleta_carrito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyCart',
            new_name='BoletaItem',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='carrito',
        ),
        migrations.AddField(
            model_name='boleta',
            name='detalleBoleta',
            field=models.ManyToManyField(related_name='carritos', to='baby.BoletaItem'),
        ),
    ]
