# Generated by Django 4.0.1 on 2022-03-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0022_rename_buycart_boletaitem_remove_boleta_carrito_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoletaItem',
            new_name='BoletaDetalle',
        ),
    ]
