# Generated by Django 4.0.1 on 2022-03-22 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0024_remove_boleta_detalleboleta_boletadetalle_boleta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletadetalle',
            name='boleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='baby.boleta'),
        ),
    ]
