# Generated by Django 4.0.1 on 2022-03-23 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0025_alter_boletadetalle_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletadetalle',
            name='boleta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='baby.boleta'),
        ),
        migrations.AlterField(
            model_name='boletadetalle',
            name='productos',
            field=models.ManyToManyField(related_name='boletaDetalle', to='baby.Product'),
        ),
    ]
