# Generated by Django 4.0.1 on 2022-03-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0027_remove_boletadetalle_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletadetalle',
            name='precioUni',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
